name: Git Pull Only

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - prod
          - dev
      notify:
        description: 'Should workflow notify team?'
        required: true
        type: boolean

jobs:
  pull-latest-code:
    runs-on: [self-hosted, ecommerce]
    name: Pull Latest Code
    # Conditional environment for approval only on prod
    environment: 
      name: ${{ github.event.inputs.environment }}
      url: ''
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Pull Latest Code from Origin
        run: |
          git pull origin master
          echo "Deploying to ${{ github.event.inputs.environment }} environment"
      
      - name: Notify Team
        if: ${{ github.event.inputs.notify }}
        run: |
          echo "Notifying team of ${{ github.event.inputs.environment }} deployment"
          # Add actual notification logic here (Slack, email, etc.)
