name: Frontend Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  pull-frontend:
    runs-on: [self-hosted, ecommerce]
    name: Pull Latest Frontend Code

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
