name: Git Pull Only

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - production
          - dev
      notify:
        description: 'Should workflow notify team?'
        required: true
        type: boolean

jobs:
  pull-latest-code:
    runs-on: [self-hosted, ecommerce]
    name: Pull Latest Code
    environment: prod  # This will require approval
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: master  # Explicitly checkout master branch
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment"
 
      - name: Pull Latest Code from Origin
        run: git pull origin master
      
      - name: Notify
        if: ${{ github.event.inputs.notify }}
        run: echo "Notifying of ${{ github.event.inputs.environment }} deployment"
