name: Git Pull Only

on:
  workflow_dispatch:

jobs:
  pull-latest-code:
    runs-on: [self-hosted, ecommerce]
    name: Pull Latest Code

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull Latest Code from Origin 
        run: git pull origin master
