name: Frontend Build & SonarQube Scan (Manual)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: [self-hosted, ecommerce]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12'

      - name: Install Dependencies
        working-directory: frontend
        run: npm install --unsafe-perm

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          /opt/sonar-scanner/bin/sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
