name: Frontend Build & SonarQube Scan (Manual)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-scan:
    name: Build Frontend & Scan with SonarQube
    runs-on: [self-hosted, ecommerce]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for proper blame data in SonarQube

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12'

      - name: Install Dependencies
        working-directory: frontend
        run: npm install --unsafe-perm

      - name: Build Frontend (ignore errors)
        working-directory: frontend
        continue-on-error: true
        run: CI=false npm run build

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.1.0  # Use the latest version
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # Use secrets instead of vars
        with:
          projectBaseDir: frontend  # Important to scan inside 'frontend'
