name: Frontend Build & SonarQube Scan (Manual)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-scan:
    name: Build Frontend & Scan with SonarQube
    runs-on: [self-hosted, ecommerce]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12'

      - name: Install Dependencies
        working-directory: frontend
        run: npm install --unsafe-perm

      - name: Build Frontend (ignore errors)
        working-directory: frontend
        continue-on-error: true
        run: CI=false npm run build

      - name: Run SonarQube Scanner
        working-directory: frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          /opt/sonar-scanner/bin/sonar-scanner -X \
            -Dsonar.projectKey=your_project_key_here \
            -Dsonar.sources=src \
            -Dsonar.inclusions=**/*.js \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
