name: Frontend Build & SonarQube Scan (Manual)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-scan:
    name: Build Frontend & Scan with SonarQube
    runs-on: [self-hosted, ecommerce]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12'

      - name: Install Dependencies
        working-directory: frontend
        run: npm install --unsafe-perm

      # 💡 Build step won't block next steps even if it fails
      - name: Build Frontend (ignore warnings)
        working-directory: frontend
        run: CI=false npm run build || true

      - name: Run SonarQube Scanner with Debug
        working-directory: frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          /opt/sonar-scanner/bin/sonar-scanner -X \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
