name: Frontend Build & SonarQube Scan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-scan:
    name: Build Frontend & Scan with SonarQube
    runs-on: [self-hosted, ecommerce]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12'

      - name: Install Dependencies
        working-directory: frontend
        run: npm install --unsafe-perm

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
