name: SonarQube Code Scan

on:
  workflow_run:
    workflows: ["Frontend Build"]  
    types:
      - completed

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: [self-hosted, ecommerce]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: frontend
