name: Frontend Build & SonarQube Scan 

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-scan:
    name: Build Frontend & Scan with SonarQube
    runs-on: [self-hosted, ecommerce]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12'  

      - name: Install Dependencies 
        working-directory: frontend
        run: npm install --unsafe-perm

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Run SonarQube Scanner
        working-directory: frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          /opt/sonar-scanner/bin/sonar-scanner \
                 -Dsonar.projectKey=ecommerce-store
                 -Dsonar.projectName=ecommerce-store \
                 -Dsonar.sources=src \
                 -Dsonar.inclusions=**/*.js \
                 -Dsonar.sourceEncoding=UTF-8 \
                 -Dsonar.host.url=http://192.168.0.104:9000 \
                 -Dsonar.login=$SONAR_TOKEN
